carts/urls.py
from unicodedata import name
from django.urls import path
from carts import views


urlpatterns = [
    # cart
    path('',views.cart,name='cart'),
    path('add-to-cart/<int:product_id>/',views.add_to_cart,name='add-to-cart'),
    path('delete_cart/<int:cart_id>/',views.delete_cart,name='delete_cart'),
    # checkout
    path('check_out/',views.check_out_view,name='check_out'),
    # buy_now
    
    path('buy_now/<int:product_id>/',views.buy_now_view,name='buy_now'),

    # ajax calls
    path('increment/<int:cart_id>/',views.cart_increment,name='increment'),
    path('decrement/<int:cart_id>/',views.cart_decrement,name='decrement'),
    # user addresee for profile
    path('user_address/',views.User_profile_address,name='user_address'),
    path('coupon_apply',views.coupon_apply_view,name='coupon_apply'),
    path('cancel_coupon',views.cancel_coupon_view,name='cancel_coupon'),
    
]

digtech/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # howe
    path('',views.home,name='home'),
    # admin
    path('amn/',include('adminpanel.urls')),
    # store
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('carts.urls')),
    # orders
    path('orders/',include('orders.urls')),
    # this is the paypal urls
     path('paypal/', include('paypal.standard.ipn.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views
app_name = 'store'

urlpatterns = [
    path('',views.store,name='Store'),
    path('<slug:slug>/',views.store,name='Store_slug'),
    path('<slug:category_slugs>/<slug:product_slug>/',views.single_product,name='single_product'),
]

templates/home/include/footer.html
   <!-- footer start -->
   {% load static %}

   <div class="container-fluid bg-dark text-secondary mt-5 pt-5" id="footer">
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
            <p class="mb-4">Shop with your desire, get in touch , Your Desire Our World</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>Kerala, Kochi</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>jithinbuasc@gmail.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+91 7592861816</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
              
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                   
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Your Email Address">
                            <div class="input-group-append">
                                <button class="btn btn-primary">Sign Up</button>
                            </div>
                        </div>
                    </form>
                    <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-square mr-2" href="https://twitter.com/mm_jithin" target="_blank"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="https://www.facebook.com/profile.php?id=100011679969977" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="https://www.linkedin.com/in/jithu-ji-4730351b3/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-primary btn-square" href="https://wa.link/o2epao" target="_blank"><i class="fab fa-whatsapp"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" href=""></a>jithinraj
                <a class="text-primary" href=""></a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'user/img/payments.png' %}" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->

templates/home/include/nav.html
  {% load static %}
  {% load crispy_forms_tags %}
  {% block css %}
  <style>
 #search_button{
   background-color: transparent;
   border: none;
    
  }
  </style>
 
      
  {% endblock css %}
  <!-- Topbar Start -->
  <div class="container-fluid">

    <!-- <div class="row bg-secondary py-1 px-xl-5">
    </div> -->
    
    <div class="row bg  bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="https://jithin-portfolio.s3.ap-south-1.amazonaws.com/portfolio_web/index.html" target="_blank" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">DIGITAL</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">TECH</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">

            <form action="{% url 'store:Store' %}" method="get">
         
            
                <div class="input-group">
                    <input type="search" name='serching_word' class="form-control" placeholder="Search for products">
                    <div class="input-group-append">
                    
                        <span class="input-group-text bg-transparent text-primary">
                          <button type="submit" id="search_button"><i class="fa fa-search"></i>
                          </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Navbar Start -->
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                  {% for link in links %}
                  <a href="{{link.get_url}}" class="nav-item nav-link">{{link.category_name}}</a>
                  {% endfor %}
              
         
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'store:Store' %}" class="nav-item nav-link">Shop</a>
                        <a href="#footer" class="nav-item nav-link">Contact</a>
                        <div class="btn-group">

                          <button id="noselect" type="button" style="border: none; background-color: transparent; width: 50px; height: 50px;" class=" btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown"><i class="text-warning fa-solid fa-fingerprint"></i></button>
                          <div class=" bg-warning dropdown-menu dropdown-menu-right">
                            {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'user_logout' %}" >Log out</a>
                            <a class="dropdown-item" href="{% url 'user_profile' %}" >User Profile</a>
                           
                            {% else %}
                            <!-- <a class="dropdown-item" href="{% url 'user_login' %}" >Sign in</a> -->
                            <a  href="{%  url 'user_register' %}" class="dropdown-item" type="button">Sign Up</a> 
                            {% endif %}

                   

                          </div>
                      </div>
                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                      {% if order_product %}
                      <a class="m-3" href="{%  url 'user_orders' %}"><i class="fa-solid fa-person-walking-luggage"></i></a> 
                      {% endif %}
                        <div class="btn-group">

                            <button id="noselect" type="button" style="border: none; background-color: transparent;" class=" btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown"><i class="fa-solid fa-right-to-bracket text-primary"></i></button>
                            <div class="dropdown-menu dropdown-menu-right">
                              {% if request.user.is_authenticated %}
                              <a class="dropdown-item" href="{% url 'user_logout' %}" >Log out</a>
                              <a class="dropdown-item" href="{% url 'user_profile' %}" >User Profile</a>
                             
                              {% else %}
                              <a class="dropdown-item" href="{% url 'user_login' %}" >Sign in</a>
                              <a  href="{%  url 'user_register' %}" class="dropdown-item" type="button">Sign Up</a> 
                              {% endif %}

                     

                            </div>
                        </div>
                        <a href="{% url 'cart' %}" class="btn px-0 ml-3"> 
                            <i class="fas fa-shopping-cart text-primary"></i>
                            
                            <span id='cart_id' class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">{{cart_count}}</span>
                        </a>
                        <!-- extra added aan ta jithine -->
                    
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>


  
  <!-- Modal -->
  <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form action="{% url 'user_register' %}">
                {{userCreationForm|crispy}}    
            </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
          
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div> -->


  <!-- user login -->
<!-- 
  <div class="modal fade" id="userLogin" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form>
                {{authenticationForm|crispy}}
                
            
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save changes</button>
        </form>
          
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div> -->