accounts/urls.py
from unicodedata import name
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from django.core.mail import send_mail


urlpatterns =[
    path('user_login/',views.userLogin,name='user_login'),
    path('user_register/',views.userRegister,name='user_register'),
    path('user_logout/',views.userLogout,name='user_logout'),
    path('otp_login/',views.otpLogin,name='otp_login'),
    path('otp_check/<int:id>/',views.otp_check,name='otp_check'),
    path('user_profile/',views.user_profile_view,name='user_profile'),
    # add address
    path('address_add',views.user_address_add,name='address_add'),
    path('address_delete/<str:address_id>/',views.address_delete_view,name='address_delete'),
    path('address_edit/<str:address_id>/',views.address_edit_view,name='address_edit'),

    # password reset views
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]

carts/urls.py
from unicodedata import name
from django.urls import path
from carts import views


urlpatterns = [
    # cart
    path('',views.cart,name='cart'),
    path('add-to-cart/<int:product_id>/',views.add_to_cart,name='add-to-cart'),
    path('delete_cart/<int:cart_id>/',views.delete_cart,name='delete_cart'),
    # checkout
    path('check_out/',views.check_out_view,name='check_out'),
    # buy_now
    
    path('buy_now/<int:product_id>/',views.buy_now_view,name='buy_now'),

    # ajax calls
    path('increment/<int:cart_id>/',views.cart_increment,name='increment'),
    path('decrement/<int:cart_id>/',views.cart_decrement,name='decrement'),
    # user addresee for profile
    path('user_address/',views.User_profile_address,name='user_address'),
    path('coupon_apply',views.coupon_apply_view,name='coupon_apply'),
    path('cancel_coupon',views.cancel_coupon_view,name='cancel_coupon'),
    
]

digtech/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # howe
    path('',views.home,name='home'),
    # admin
    path('amn/',include('adminpanel.urls')),
    # store
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('carts.urls')),
    # orders
    path('orders/',include('orders.urls')),
    # this is the paypal urls
     path('paypal/', include('paypal.standard.ipn.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
from django.utils import timezone
import random
from django.core.validators import RegexValidator

# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self,first_name,last_name,username,email,password,**other_fields):
        if not email:
            raise ValueError('The Email is mandatory')
        if not username:
            raise ValueError('The username is mandatory')

        user = self.model(
            email= self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,**other_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,first_name,last_name,username,email,password,**other_fields):

        other_fields.setdefault('is_staff',True)
        other_fields.setdefault('is_superuser',True)
        other_fields.setdefault('is_active',True)
        other_fields.setdefault('is_admin',True)
        
    #  this is and validation checkup while creation method
        if other_fields.get('is_staff') is not True:
            raise ValueError('Super user is_staff must be True')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('is_superuser must set to True')
        if other_fields.get('is_active') is not True:
            raise ValueError('is_active must be set to True')
        if other_fields.get('is_admin') is not True:
            raise ValueError('is_admin must be set to True')

        return self.create_user(first_name,last_name,username,email,password,**other_fields)
    

class Account(AbstractBaseUser,PermissionsMixin):
    ''' This is the user models which created the help of abstract Base User , we need to 
    write every things from the scratch in this AbstractBaseUser '''

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=100,unique=True)
    email = models.EmailField(max_length=100,unique=True)
    phone = models.CharField(max_length=20)

    # extra added tta 
    #required 
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','first_name','last_name']

    def __str__(self):
        return self.email


class UserProfile(models.Model):

    
    user = models.OneToOneField(Account,on_delete=models.CASCADE,related_name='profile')
    profile_pic = models.ImageField(upload_to='profile/',max_length=500,default='profile/avatar.png')
    # 
    first_name = models.CharField(max_length=50,null=True)
    last_name = models.CharField(max_length=50,null=True)
    username = models.CharField(max_length=100,null=True)
    email = models.EmailField(max_length=100,null=True)
    phone = models.CharField(max_length=15, validators=[RegexValidator(r'^\d{1,15}$')])
    address_line_1 = models.TextField(max_length=300,null=True)
    address_line_2 = models.TextField(max_length=300,null=True)
    country = models.CharField(max_length=50,null=True)
    state = models.CharField(max_length=50,null=True)
    city = models.CharField(max_length=50,null=True)

    def __str__(self):
        return self.user.username

class UserAddress(models.Model):
    STATUS = (
        ('HOME', 'HOME'),
        ('OFFICE', 'OFFICE'),
        ('OTHERS', 'OTHERS'),
    )
    
    user = models.ForeignKey(Account,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=15, validators=[RegexValidator(r'^\d{1,15}$')])
    address_line_1 = models.TextField(max_length=300)
    address_line_2 = models.TextField(max_length=300)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    type = models.CharField(max_length=10, choices=STATUS, default='HOME')

    def __str__(self):
        return self.first_name+' '+ self.last_name
    

accounts/forms.py
from accounts.models import Account #starting here
from django.contrib.auth.forms import UserCreationForm
from django import forms

from accounts.models import UserProfile,UserAddress
from PIL import Image
from django.core.files import File


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = Account
        fields = ['first_name','last_name','email','phone','password1','password2']
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None


class UserProfileForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=Account.objects.all(), widget=forms.HiddenInput())
    address_line_1 = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'cols': 20}))
    address_line_2 = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'cols': 20}))
    profile_pic = forms.ImageField(widget=forms.FileInput,)

    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = UserProfile
        fields = ['x','y','width','height','user','first_name','last_name','username','email','phone','address_line_1','address_line_2','country','state','city','profile_pic']

    def save(self):

        photo = super(UserProfileForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.profile_pic)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        print(resized_image,'resized_image')
        resized_image.save(photo.profile_pic.path)

            
        return photo

# user address form
class UserAddressForm(forms.ModelForm):

    address_line_1 = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'cols': 20}))
    address_line_2 = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'cols': 20}))
    
    class Meta:
        model = UserAddress
        fields = ['first_name','last_name','email','phone','address_line_1',
                   'address_line_2','country','state','city']

accounts/views.py
from email import message
from multiprocessing import context
from django.shortcuts import render,redirect

from accounts.forms import CustomUserCreationForm, UserAddressForm, UserProfileForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login,logout

from accounts.models import Account, UserAddress
from django.contrib import messages
import random
from accounts.util import send_sms
# database tables
from carts.models import Cart,CartItems
from carts.views import _get_cart_id

import requests
# Create your views here.

# user profile
from accounts.models import UserProfile


def userLogin(request):

    if request.user.is_authenticated:
        return redirect('home')
    forms = AuthenticationForm()
    if request.method == 'POST':
        forms = AuthenticationForm(request,data = request.POST)

        if forms.is_valid():

            username = forms.cleaned_data.get('username')
            password = forms.cleaned_data.get('password')
            print(password,'jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj')
  
            user = authenticate(username=username,password=password)
            if user is not None:
                try:
                    cart = Cart.objects.get(cart_id=_get_cart_id(request))
                    cart_items_exists = CartItems.objects.filter(cart=cart).exists()
                    if cart_items_exists:
                        cart_items = CartItems.objects.filter(cart=cart)
                        
                        cart_items_user_exist = CartItems.objects.filter(user=user).exists()
                        if cart_items_user_exist:
                            cart_items_user = CartItems.objects.filter(user=user)
                            for items in cart_items:
                                for user_item in cart_items_user:
                                    if items.product == user_item.product:

                                        user_item.quantity = items.quantity + user_item.quantity
                                        items.delete()
                                        user_item.save()
                        else:
                            for items in cart_items:
                                items.user = user
                                items.save()
                except :
                    pass
                login(request,user)
                url = request.META.get('HTTP_REFERER')
                try:
                    query = requests.utils.urlparse(url).query
                    # ?next=/cart/check_out/
                    path = query.split('=')
                    
                    return redirect(path[1])
                except:
                    pass
                

    return render(request,'accounts/userlogin.html',{'authenticationForm': forms})

def userRegister(request):

    forms = CustomUserCreationForm(request.POST or None)

    if request.method == 'POST':
        if forms.is_valid():

           new_user =  forms.save(commit=False)
           username = new_user.email[0:new_user.email.index('@')]
           new_user.is_active = True
           new_user.username = username
           new_user.save()
           login(request, new_user)
           return redirect('home')

    return render(request,'accounts/userregister.html',{'creationForms':forms})

def otpLogin(request):

    otp_mobile= True

    if request.method == 'POST':
        mobile_number = request.POST.get('mobile_number')
        if Account.objects.filter(phone=mobile_number).exists():
            user = Account.objects.get(phone=mobile_number)
            number_list = [i for i in range(10)]
            code_list = []
            for number in range(4):
                random_number = random.choice(number_list)
                code_list.append(random_number)
            string_number = "".join(str(item) for item in code_list)
            request.session['otp_code'] = string_number
            send_sms(string_number,user.phone)
            return redirect('otp_check',id=user.id)
        else:
            messages.error(request, 'The phone number is not registerd')

    return render(request,'accounts/otplogin.html',{'otp_mobile':otp_mobile})

# this method is checking the phone number is existing in the database
def otp_check(request,id):

    user = Account.objects.get(id=id)
    otp_mobile= False      
    if request.method == "POST":
        otp_from_user = request.POST.get('otp')
        otp_code = request.session.get('otp_code')
        
        
        if  otp_code == otp_from_user:
            if request.session.get('otp_code'):
                del request.session['otp_code']
            login(request,user)
            return redirect('home')
        else:
            messages.error(request,'The otp is not correct')
            
    return render(request,'accounts/otplogin.html',{'otp_mobile':otp_mobile})


# this is for the forget password 
def forgot_password_view(request):
    pass
# user Proifle views
def user_profile_view(request):

    user_profile = UserProfile.objects.get(user=request.user)
    user = Account.objects.get(id=request.user.id)
    form = UserProfileForm(instance=user_profile)
    orders = user.orderproduct_set.all()
    if request.method == 'POST':
        form = UserProfileForm(request.POST,request.FILES,instance=user_profile)
       
        if form.is_valid():
            form.save()
            return redirect('user_profile')
        else:
            pass

    context = {
        'user_profile': user_profile,
        'orders': orders[:4],
        'form': form,
    }
    return render(request,'accounts/user_profile.html',context)


def user_address_add(request):

    address_add = True

    form = UserAddressForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            messages.success(request,'Address Addedd')
            print('hello hai')
            url = request.META.get('HTTP_REFERER')
            return redirect('check_out')
        else:
            messages.error(request,'Try again ')
    context = {
        'form':form,
        'address_add': address_add,
    }
    return render(request,'accounts/address_add.html',context)

def address_edit_view(request,address_id):

    print(address_id)
    address = UserAddress.objects.get(id=address_id)
    form = UserAddressForm(instance=address)
    if request.method == "POST":
        form = UserAddressForm(request.POST,instance=address)
        if form.is_valid():
            form.save()
            return redirect('check_out')
    context = {
        'form':form
    }
    return render(request,'accounts/address_add.html',context)

def address_delete_view(request,address_id):
    address = UserAddress.objects.get(id=address_id)
    address.delete()
    messages.success(request,'Deleted success fully')
    return redirect('user_profile')

def userLogout(request):
    logout(request)
    return redirect('home')

templates/accounts/user_profile.html
{% extends "home/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
<style>
    body{
        background-image: url('https://cdn.pixabay.com/photo/2018/03/11/12/14/raindrops-3216607__340.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
       
  
    }


   .bg{
    background-image: url('https://cdn.pixabay.com/photo/2018/03/11/12/14/raindrops-3216607__340.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
   }
   .alert_div{
  background-color: rgba(46, 46, 33, 0.557); display: flex; justify-content: space-between;
   }
   .hide{
     display: none;
   
   }
   .asteriskField {
    display: none;
}
label{
color: black;
font-weight: bolder;
}
span{
  display: none;
}

input[type="file"]{
  background-color: yellow;

}

html {
    overflow: scroll;
    overflow-x: hidden;
}
::-webkit-scrollbar {
    width: 0;  /* Remove scrollbar space */
    background: transparent;  /* Optional: just make scrollbar invisible */
}
/* Optional: show position indicator in red */
::-webkit-scrollbar-thumb {
    background: #FF0000;
}

 
</style>
<link href="{% static 'admin/css/cropper/cropper.min.css' %}" rel="stylesheet">

{% endblock css %}

{% block base %}
<div class="row">
    <div class="col-md-4 p-5 text-white " >

        <div class="card p-3" style="background-color: rgba(5, 5, 5, 0.441);" >
          <div class="row justify-content-center">
            <img class="card-img-top" src="{{user_profile.profile_pic.url}}" style=" height: 350px; width: 350px; border-radius: 50%;" alt="Card image cap">
          </div>
            
            <div class="card-body">
              <h5 class="card-title text-white text-center">{{user_profile.user.username}}</h5>
              <h6 class="text-white text-center">{{user_profile.user.email}}</h6>
   
              <h6 class="text-white text-center">{{user_profile.user.phone}}</h6>
              <div class="row">
                <button data-toggle="modal" data-target="#userpocket" class="btn btn-outline-warning">Pockets</button>
              </div>

            </div>
          </div>
      
    </div>

    <div class="col-md-8 p-5 text-white">  
        <div class="row">
            <div class="card p-3" style="background-color: rgba(3, 29, 69, 0.626); " >
              <div class="row p-3">
                <div class="col-md-6 " style="background-color: rgba(0, 0, 0, 0.295);">
                  <div class="card-body ">
                    <h5 class="card-title text-white text-center">{{user_profile.username}}</h5>
                    <h6 class="text-white text-center">{{user_profile.email}}</h6>
         
                    <h6 class="text-white text-center">{{user_profile.phone}}</h6>
                    <div class="row">
                        <div class="col-md-4">
                          <a data-toggle="modal" data-target="#userEdit" class="btn btn-outline-warning">EDIT</a>
                        </div>
                      
                    </div>
      
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="card-body " style="background-color: rgba(0, 0, 0, 0.295);" >
                    {% if user_profile.address_line_1 %}
                    <h5 class="card-title text-white text-center">{{user_profile.address_line_1}}</h5>
                    <h6 class="text-white text-center">{{user_profile.address_line_2}}</h6>
                    {% else %}
                    <div class="alert" id=""   role="alert">
                    
                      <div class="col-md-8 " style="display: flex; gap: 20px;">
              
                        <h6>Don't Forgot To Choose Adress</h6>
                      </div>

                     
                    </div>
                    {% endif %}

              
      
                  </div>
                </div>

              </div>

              </div>
        </div>
        <div class="row mt-5">
            <div class="card p-3" style="background-color: rgba(3, 29, 69, 0.626); " >

                <div class="card-body">
                  {% for order in  orders %}
                  
                  <div class="alert alert_div" id="alert-{{order.id}}"   role="alert">
                    
                    <div class="col-md-8" style="display: flex; gap: 20px;">
                      <img src="{{order.product.image_2.url}}" class="text-start" alt="" style="width: 25px; height: 25px; border-radius: 50%;">
                      <h6 class="text-white">{{order.product.product_name}}</h6>
                      <h6 class="text-white">{{order.created_at|timesince}}</h6>
                      <h6></h6>
                    </div>

                    <div class="col-md-3 text-end">
                      <i data-id="{{order.id}}" class="close_btn fa-solid fa-xmark"></i>
                    </div>
                   
                  </div>
                  {% endfor %}

                </div>
              </div>
        </div>

    </div>
</div>

<div class="modal fade" id="userpocket" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="userEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content " style="border: 3px black solid;">
      <div class="modal-header" style="border-bottom: 3px black solid;">
        <h5 class="modal-title" id="exampleModalLongTitle">Edit Your address</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row  p-3">
      <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div style="display: none;">
                {{form.user|as_crispy_field}}
            </div>
            <div class="row">
              <div class="col-md-12 form-group">
                {{form.username|as_crispy_field}}
            </div>
            </div>
            <div class="row">
                <div class="col-md-6 form-group">
                  {{form.first_name|as_crispy_field}}
              </div>
              <div class="col-md-6 form-group">
                  {{form.last_name|as_crispy_field}}
              </div>
            </div>
       
            <div class="row">
                <div class="col-md-6 form-group">
                    {{form.email|as_crispy_field}}
                </div>
                <div class="col-md-6 form-group">
                  {{form.phone|as_crispy_field}}
                </div>
            </div>

          <div class="row">
                <div class="col-md-6 form-group">
                  {{form.address_line_1|as_crispy_field}}
              </div>
              <div class="col-md-6 form-group">
                  {{form.address_line_2|as_crispy_field}}
              </div>
          </div>

          <div class="row">
              <div class="col-md-6 form-group">
                {{form.country|as_crispy_field}}
            </div>
            <div class="col-md-6 form-group">
              {{form.state|as_crispy_field}}
            </div>
          </div>
  
          <div class="row">
                <div class="col-md-6 form-group">
                  {{form.city|as_crispy_field}}
              </div>
              <div class="col-md-6 form-group">
                {{form.profile_pic|as_crispy_field}}
              </div>
          </div>

          {{form.x}}
          {{form.y}}
          {{form.width}}
          {{form.height}}

      </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
      </div>
  </div>
</div>
</div>

<!-- User profile cropping image modal  -->
<div class="modal fade" id="modalCrop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Crop the photo</h4>
      </div>
      <div class="modal-body">
        <img src="" id="image" style="max-width: 100%;">
      </div>
      <div class="modal-footer">
        <div class="btn-group pull-left" role="group">
          <button type="button" class="btn btn-default js-zoom-in">
            <span class="glyphicon glyphicon-zoom-in"></span>
          </button>
          <button type="button" class="btn btn-default js-zoom-out">
            <span class="glyphicon glyphicon-zoom-out"></span>
          </button>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
        <button type="button" class="btn btn-primary" id="js-crop-and-upload">Crop and upload</button>
      </div>
    </div>
  </div>
</div>
<!-- the user cropping modal end here -->
<!-- address add options  -->
<div class="modal fade" id="addressAdd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color: rgba(0, 0, 0, 0.566);">
      <div class="modal-header">
        <h5 class="modal-title text-white text-center" id="exampleModalLabel">ADDRESS</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span class="text-white" aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form action="{% url 'address_add' %}" method="POST">
              {% csrf_token %}
              {{addressForm|crispy}}
          
        
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save changes</button>
      </form>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>




{% endblock base %}

{% block scripts %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="{% static 'admin/crop/cropper.min.js' %}"></script>
<script>
  const close_order_buttons = [...document.getElementsByClassName('close_btn')]

  close_order_buttons.forEach(Element=>{
    Element.addEventListener('click',function(){
      const id = Element.dataset.id
      const alert_box = document.getElementById( `alert-${id}`)
      alert_box.classList.add('hide')
    
    })
  })

  // cropping images
  
// this function for the image 1 cropping
$(function () {

/* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
$("#id_profile_pic").change(function () {
  if (this.files && this.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $("#image").attr("src", e.target.result);
      $("#modalCrop").modal("show");
    }
    reader.readAsDataURL(this.files[0]);
  }
});

/* SCRIPTS TO HANDLE THE CROPPER BOX */
var $image = $("#image");
var cropBoxData;
var canvasData;
$("#modalCrop").on("shown.bs.modal", function () {
  $image.cropper({
    viewMode: 1,
    aspectRatio: 1/1,
    minCropBoxWidth: 200,
    minCropBoxHeight: 200,
    ready: function () {
      $image.cropper("setCanvasData", canvasData);
      $image.cropper("setCropBoxData", cropBoxData);
    }
  });

}).on("hidden.bs.modal", function () {
  cropBoxData = $image.cropper("getCropBoxData");
  canvasData = $image.cropper("getCanvasData");
  $image.cropper("destroy");
});

$(".js-zoom-in").click(function () {
  $image.cropper("zoom", 0.1);
});

$(".js-zoom-out").click(function () {
  $image.cropper("zoom", -0.1);
});



/* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */


$("#js-crop-and-upload").click(function () {
  var cropData = $image.cropper("getData");

  $("#id_x").val(cropData["x"]);
  $("#id_y").val(cropData["y"]);
  $("#id_height").val(cropData["height"]);
  $("#id_width").val(cropData["width"]);
  $("#modalCrop").modal("hide");
  const url = document.createElement("canvas").toDataURL
  console.log(cropData)
    // console.log(url,'jitine ithaaada cropped datayude upayogam');

});

});



</script>
      
{% endblock scripts %}

templates/accounts/userlogin.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}

{% block base %}
<div class="row justify-content-center"  >
    <div class="col-md-3 p-5 text-white " style="height:400px; background-color:rgb(61,70,77); border-radius: 20px;">
        <form action="{% url 'user_login' %}" method="POST">
            {% csrf_token %}
            {{authenticationForm}}
        <div class="row justify-content-center text-center">
            <button class="btn w-25 btn-warning">Login </button>
        </form> 
            <p class="mt-3">Dont you have the account?<a href="{% url 'user_register' %}">SignUp</a></p>
            <p class="mt-3">OTP login<a href="{% url 'otp_login' %}">Otp Login</a></p>
        </div>
       
    </div>
</div>


{% endblock base %}

{% include "home/include/footer.html" %}