adminpanel/urls.py
from unicodedata import name
from django.urls import  path
from adminpanel import views



urlpatterns = [

    path('',views.adminHome, name='adminhome'),
    path('adminLogin/',views.adminLogin,name='adminLogin'),
    path('adminregister/',views.admin_register,name='adminregister'),
    path('adminLogout/',views.admin_logout,name='adminLogout'),

    # user management
    path('usermanagement/active_inactive/',views.active_inactive_user,name='active_inactive'),
    path('usermanagement/',views.user_management,name='usermanagement'),

    # product management
    path('product_view/',views.product_view,name='product_view'),
    path('product_view/testing', views.single_product, name='single_product'),
    path('product_add/',views.product_add,name='product_add'),
    path('product_update/<int:id>/',views.product_update,name='product_update'),
    path('product_delete/<int:id>/',views.product_delete,name='product_delete'),

    # category management
    path('category_view/', views.category_view, name='category_view'),
    path('category_delete/<int:id>/', views.category_delete, name='category_delete'),
    path('category_edit/<int:id>/', views.category_edit, name='category_edit'),

    # order management
    path('order_view',views.order_management_view,name='order_view'),
    path('order_cancel_admin/<str:order_id>/',views.order_cancel_view,name='order_cancel_admin'),
    path('order_products/',views.order_product_table,name='order_products'),
    path('order_edit/<str:order_id>/',views.order_edit_view,name='order_edit'),

    # coupon_management_view
    path('coupon_management',views.coupon_management_view,name='coupon_management'),
    path('delete_coupon/<str:coupon_id>/',views.delete_coupon_view,name='delete_coupon'),
    path('update_coupon/<str:coupon_id>/',views.update_coupon_view,name='update_coupon'),
    path('active_coupon/<str:coupon_id>/',views.active_coupon_view,name='active_coupon'),
    path('coupon_add/',views.coupon_add_view,name='coupon_add'),

    # product_offer 
    path('product_offer_management/',views.product_offer_mangement_view,name='product_offer_management'),
    path('delete_product_offer/<str:id>/',views.delete_product_offer_view,name='delete_product_offer'),
    path('update_product_offer/<str:id>/',views.edit_product_offer_view,name='update_product_offer'),
    path('active_deactive_product_offer/<str:id>/',views.active_deactive_product_offer_view,name='active_deactive_product_offer'),

    # category offer urls 
    path('category_offer/',views.category_offer_view,name='category_offer'),
    path('delete_category_offer/<str:id>/',views.delete_category_offer_view,name='delete_category_offer'),
    path('update_category_offer/<str:id>/',views.edit_category_offer_view,name='update_category_offer'),
    path('active_deactive_category_offer/<str:id>/',views.active_deactive_category_offer_view,name='active_deactive_category_offer'),

    # admin report urls
    path('admin_report/',views.admin_report_view,name='admin_report'),
 
    
    
    


    

    
]

carts/urls.py
from unicodedata import name
from django.urls import path
from carts import views


urlpatterns = [
    # cart
    path('',views.cart,name='cart'),
    path('add-to-cart/<int:product_id>/',views.add_to_cart,name='add-to-cart'),
    path('delete_cart/<int:cart_id>/',views.delete_cart,name='delete_cart'),
    # checkout
    path('check_out/',views.check_out_view,name='check_out'),
    # buy_now
    
    path('buy_now/<int:product_id>/',views.buy_now_view,name='buy_now'),

    # ajax calls
    path('increment/<int:cart_id>/',views.cart_increment,name='increment'),
    path('decrement/<int:cart_id>/',views.cart_decrement,name='decrement'),
    # user addresee for profile
    path('user_address/',views.User_profile_address,name='user_address'),
    path('coupon_apply',views.coupon_apply_view,name='coupon_apply'),
    path('cancel_coupon',views.cancel_coupon_view,name='cancel_coupon'),
    
]

digtech/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # howe
    path('',views.home,name='home'),
    # admin
    path('amn/',include('adminpanel.urls')),
    # store
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('carts.urls')),
    # orders
    path('orders/',include('orders.urls')),
    # this is the paypal urls
     path('paypal/', include('paypal.standard.ipn.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminpanel/models.py
from django.db import models
from category.models import Category
from store.models import Product
import datetime
from django.core.validators import MaxValueValidator,MinValueValidator

# Create your models here.
class Admin(models.Model):
    
    admin_name = models.CharField(max_length=100,unique=True)
    password = models.CharField(max_length=100)
    is_logedinn = models.BooleanField(default=False)

    @property
    def loginornot(self):
        return self.is_logedin


    def admin_authenticate(self,name,password):
        if self.admin_name == name and self.password == password:
            self.is_logedinn = True
            return True
        else:
            return False

    def admin_logout(self):
        self.is_logedin = False
    
    def __str__(self):
        return self.admin_name


# category offer
class CategoryOffer(models.Model):

    now = datetime.date.today()

    category = models.OneToOneField(Category,related_name='catoffer',on_delete=models.CASCADE)
    offer_percentage = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(50)])
    valid_from = models.DateField()
    valid_to = models.DateField()
    active = models.BooleanField(blank=True,null=True)

    def __str__(self):
        return self.category.category_name


    @property
    def category_offer_check(self):

        if self.valid_from < self.now and self.valid_to >self.now and self.active == True  :
            return True
        else:
            return False
    def category_offer_price(self,product):

        if self.category_offer_check:
            return (product.price) - (product.price) * (self.offer_percentage /100)
        else:
            return (product.price)


class ProductOffer(models.Model):

    now = datetime.date.today()

    product = models.OneToOneField(Product,related_name='product_off',on_delete=models.CASCADE)
    offer_percentage = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(50)])
    valid_from = models.DateField()
    valid_to = models.DateField()
    active = models.BooleanField(blank=True,null=True)

    def __str__(self):
        return self.product.product_name

    @property
    def product_offer_check(self):

        if self.valid_from < self.now and self.valid_to >self.now and self.active == True :
            return True
        else:
            return False

    def product_offer_price(self,product):

        if self.product_offer_check:
            return (product.price) - (product.price) * (self.offer_percentage /100)
        else:
            return (product.price)

category/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=50,unique=True)
    category_slug = models.SlugField(max_length=100,unique=True)
    description = models.TextField(max_length=500,blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    def get_url(self):
        return reverse('store:Store_slug',args=[self.category_slug])

    def __str__(self):
        return self.category_name

adminpanel/views.py
# project directory



from django.shortcuts import render,redirect # this is the start
import datetime
from django.http import JsonResponse,HttpResponse

from adminpanel.models import Admin, CategoryOffer, ProductOffer
from adminpanel.forms import AdminForm
from django.contrib import messages
from accounts.models import Account
import json 
from adminpanel.decorator import adminlogin,logout
from category.models import Category
from orders.context import order_product
from store.models import Product
from adminpanel.forms import ProductForm,CategoryForm,CategoryOfferForm,ProductOfferForm
import os
from adminpanel.forms import OrderFilter

from orders.models import Order,OrderProduct, Payment


# order Edit Form for admin
from orders.forms import OrderFormEdit
from accounts.models import Account
from django.db.models import Avg, Count, Min, Sum
from django.db.models.functions import TruncMonth

# coupon models from cart
from carts.models import Coupon
from adminpanel.forms import CouponForm
# pdf convertion packages
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
# table views 
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle,Paragraph
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm

# this is for the csv file
import csv  
# for paginator
from django.core.paginator import Paginator

#admin home
@logout
def adminHome(request):

    users = Account.objects.all()
    orders = Order.objects.all()
    total_orders = orders.count()
    cancelled_orders = Order.objects.filter(status='Cancelled')
    completed_orders = Order.objects.filter(status='Completed')
    accepted_orders = Order.objects.filter(status='Accepted')
    new_orders = Order.objects.filter(status='New')

    payment_details = Payment.objects.all()
    payment_completd = Payment.objects.filter(status='COMPLETED')
    pending_completd = Payment.objects.filter(status='PENDING')
    order_revenue = Payment.objects.all()
    orderd_products = OrderProduct.objects.filter(ordered=True)
    today = datetime.date.today()
    year_wise = Order.objects.filter(created_at__year = today.year) 
                     
    # aggrecation error int + str not support 
    # total_income = Order.objects.aggregate(sum('order_total'))
    total_revenue = 0
    for amounts in order_revenue:

        if isinstance(amounts.amount, str):
            total_revenue+= float(amounts.amount)
        else:
            total_revenue += amounts.amount

    today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
    today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
    today_registerd_users = Account.objects.filter(date_joined__range=(today_min, today_max))
    today_revenue_list = Payment.objects.filter(created__range=(today_min, today_max))
    
    today_revenue= 0
    for amounts in today_revenue_list:
        if isinstance(amounts.amount, str):
            today_revenue+= float(amounts.amount)
        else:
            today_revenue += amounts.amount
    

    payment_methods = {}
    if Payment.objects.filter(payment_method='COD').exists():
        cod = Payment.objects.filter(payment_method='COD')
    else:
        cod = None
    if Payment.objects.filter(payment_method='PAYPAL').exists():
        paypal = Payment.objects.filter(payment_method='PAYPAL')
    else:
        paypal = None
    payment_method_type = None

    # this is checking the count of  paypal and cod,
    if cod and paypal:
        if cod.count() > paypal.count():

            payment_methods = cod
            payment_method_type= cod[0]
        else:
            payment_methods = paypal
            payment_method_type= paypal[0]
    
    
    context = {
    'total_orders': total_orders,
    'total_revenue':round(total_revenue,2),
    'users':users,
    'today_registerd_users':today_registerd_users,
    'cancelled_orders':cancelled_orders,
    'cod':cod,
    'paypal': paypal,
    'payment_methods':payment_methods,
    'payment_method_type':payment_method_type,
    'today_revenue':round(today_revenue,2),
    'cod': cod,
    'paypal': paypal,
    'orderd_products':orderd_products,
    'payment_details':payment_details,
    'completed_orders':completed_orders,
    'accepted_orders':accepted_orders,
    'new_orders':new_orders,
    'payment_completd':payment_completd,
    'pending_completd':pending_completd,
    'year_wise':year_wise,
    'order_revenue':order_revenue,
     }
    return render(request,'adminindex.html',context)

@adminlogin
def adminLogin(request):

    form = AdminForm(request.POST or None)
    if request.method == 'POST':
        user_name = request.POST.get('admin_name')
        password1 = request.POST.get('password')

        if Admin.objects.filter(admin_name=user_name,password=password1).exists():
            user = Admin.objects.get(admin_name=user_name,password=password1)
            authenticated = user.admin_authenticate(user_name,password1)
            if authenticated:
                request.session['id']=user.id
                
                return redirect('adminhome')
        else:
            messages.error(request, 'Not valid credentials')

    context = {
            'form':form
        }

    return render(request,'adminlogin.html',context)


#admin register
@adminlogin
def admin_register(request):

    form = AdminForm()
    if request.method == "POST":
        form = AdminForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('adminLogin')

    context = {
        'form': form
    }
    return render(request,'adminregister.html',context)


# admin logout
def admin_logout(request):

    if 'id' in request.session:
        request.session.flush()
        return redirect('adminLogin')
    


# user management
@logout
def user_management(request):
    users  = Account.objects.all()

    user_paginator = Paginator(users,5)
    page_number = request.GET.get('page')
    paginated_users = user_paginator.get_page(page_number)

    context = {
        'users': paginated_users,
    }
 
    return render(request,'usermanagement.html',context)

# ajax used put method for activatin the user and inactivate the user
def active_inactive_user(request):

    if request.method == 'PUT':

        # taking the data from the request
        data1 = json.load(request)
        ajax_id = data1.get('id')
        user = Account.objects.get(id=ajax_id)

        # changing the is_active to opposite value
        user.is_active = not user.is_active
        user.save()
        user_active_value = user.is_active

        context = {
            'user_active_value': user_active_value
                }
        return JsonResponse(context)  
    return JsonResponse({'hai':'hello'})


# product management start here
# product_view
@logout
def product_view(request):

    product_form = ProductForm()
    products = Product.objects.all()
    product_count = products.count()
    category_count = Category.objects.all().count()
    product_paginator = Paginator(products,5)
    page = request.GET.get('page')
    products = product_paginator.get_page(page)

    context = {

        'products':products,
        'product_count': product_count,
        'category_count': category_count,
        'product_form': product_form,

    }
    return render(request,'product_management.html',context) 

# ajax call for viewing the product

def single_product(request):
    product_id = request.GET.get('id')

    try:
        product = Product.objects.get(id=product_id)       
                
    except Exception as e:
        raise e

    categories = Category.objects.all()
    count = 0

    for categor in categories:
        count = count+1
        if categor.category_name == product.category.category_name:
            break
    


    items ={

        'id': product.id,
        'name': product.product_name,
        'slug': product.slug,
        'category': product.category.category_name,
        'price': product.price,
        'stock': product.stock,
        'description': product.description,
        'image_1': product.image_1.url,
        'image_2': product.image_2.url,
        'image_3': product.image_3.url,
        'image_4': product.image_4.url,
        'category_count': count,

    }
    


    return JsonResponse({'products':items})
# product add
@logout
def product_add(request):

    form = ProductForm()
    if request.method == 'POST': 
        form = ProductForm(request.POST, request.FILES)  
        if form.is_valid():
            form.save()
            return redirect('product_view')
    
    context = {
        'product_form':form,
    }
    return render(request,'product_add.html',context)

# PRODUCT DELETE
@logout
def product_delete(request,id):

    if Product.objects.filter(id=id).exists():
        product = Product.objects.get(id=id)
        product.delete()
        messages.success(request, 'Deleted success fully')
        return redirect('product_view')
        
    else:
        messages.error(request, 'Product is not available')
        return redirect('product_view')
# PRODUCT UPDATE
@logout
def product_update(request,id):

    if Product.objects.filter(id=id).exists():
        product = Product.objects.get(id=id)
    else:
        return redirect('product_view')

    product_form = ProductForm(instance=product)

    if request.method == "POST":
        product_form = ProductForm(request.POST,request.FILES,instance=product)
        print(product_form)
        if product_form.is_valid():
           
            image1_path = product.image_1.path
            image2_path = product.image_2.path
            image3_path = product.image_3.path
            image4_path = product.image_4.path
            path_list = []

adminpanel/templates/category_edit.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
<style>
*{
margin: 0;
} 
input[type='file'] {
  color: rgba(0, 0, 0, 0);

}
input[type=file]::file-selector-button {
  border: 2px solid #e7e55c;
  padding: .2em .4em;
  border-radius: .2em;
  background-color: rgb(209,161,14);
  transition: 1s;
}
.hide{
  display: none;
}
  .product_name{
    color: black;
    font-weight: bolder;
    font-size: 15px;
    position: absolute;
 
  }
  .asteriskField {
    display: none;
}
label{
    color: white;
}
</style>
  
{% endblock css %}
{% block adminbase %}
  
{% include "base/sidebar.html" %}

<main class="main-content position-relative  h-100 border-radius-lg " style="height: 50%;">
    {% include "base/nav.html" %}
        <div class="row justify-content-center" style="height: 100vh;">
            <div class="col-md-5   m-5 bg-dark p-5" style="border-radius:15px;">
                <form   method="POST" action=".">
                          {% csrf_token %}
                          {{category_edit_form|crispy}}
                          
                            
                            <div class="row justify-content-center mt-2">
                                <button type="submit" class="w-50 btn btn-warning p-2 text-center" >UPDATE</button>
                            </div>
                </form>
            </div>
        </div>
    {% include "base/footer.html" %}
  </main>
  
<!-- this is the script for user management -->
  {% block scripts %}
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>

  <script>



// automatic creating slug fields
$('#id_category_name').keyup(function() {
    var dInput = this.value;
    $('#id_category_slug').val(dInput)
});
  </script>
  
  {% endblock scripts %}




  {% endblock adminbase %}

adminpanel/templates/category_management.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
<style>
  Label{
    color: white;
  }
  .alert-error{
    background-color: rgba(255, 0, 0, 0.377);
  }
</style>
  
{% endblock css %}

{% block adminbase %}
  
{% include "base/sidebar.html" %}

<main class="main-content position-relative  h-100 border-radius-lg " style="height: 100%;">
    {% include "base/nav.html" %}
    {% block pagename %}
      <b>CATEGORY MANAGEMENT</b> 
    {% endblock pagename %}
    <div class="container-fluid py-4">
      <div class="row">
        <div class="row justify-content-start">
          {% if messages %}
                

          {% for message in messages %}
        
            <div class="alert col-md-8 alert-{{ message.tags }} text-center" role="alert">
                  {{ message }}
            </div>

          {% endfor %}
              
                
          {% endif %}
</div>
        <div class="col-md-8">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3" style="display: flex; justify-content: space-between; ">
                <div style="display: flex; justify-content: space-between;">
                      <div style="border-right: 3px rgb(247, 243, 243) solid;">
                        <h6 style="margin-right: 10px;" class="text-dark text-capitalize ps-3"> <b>Total {{ category_count }} Categories</b></h6>
                      </div>
                      <!-- {% for key, value in cat_product_count.items  %}
                      <div style="border-right: 3px rgb(247, 243, 243) solid;">
                        <h6 style="margin-right: 10px;" class=" text-capitalize ps-3 text-dark"><b> {{key}}-{{value}} products</b></h6>
                      </div>
                      {% endfor %} -->
                </div>
                <div style="margin-right: 20px;">
                  <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#categoryadd">
                    <b>+</b>
                  </button>
           
                </div> 
               
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-dark text-xxs font-weight-bolder opacity-7"><b>Category Name</b></th>
                      <th class="text-uppercase text-dark text-center text-xxs font-weight-bolder opacity-7"><b>Description</b></th>
                      <th class="text-uppercase text-dark text-center text-xxs font-weight-bolder opacity-7"><b>delete</b></th>
                      <th class="text-uppercase text-dark text-center text-xxs font-weight-bolder opacity-7"><b>Edit</b></th>
                    </tr>
                  </thead>
                  <tbody>

                    {% for category in  categories %}
                    <tr>
                        <td>
                          <div class="d-flex px-2 py-1">
    
                            <div class="d-flex flex-column justify-content-center">
                              <h6 class="mb-0 text-sm">{{category.category_name}}</h6>
                         
                            </div>
                          </div>
                        </td>
                 

                        <td class="align-middle text-center">
                          <span class="text-secondary text-xs font-weight-bold">{{category.description}}</span>
                        </td>
                        <td class="align-middle text-center text-sm">
                          <a  href="{% url 'category_delete' category.id %}" class="product_details  text-xs font-weight-bold"><h5><i class="text-danger fa-solid fa-trash"></i></h5></a>
                        </td>
                        <td class="align-middle text-center text-sm">
                          <a href="{% url 'category_edit' category.id %}" class="text-xs font-weight-bold"><h5><i class="text-success fa-solid fa-pen-to-square"></i></h5></a>
                        </td>
                     
                      </tr>
                     
                    {% endfor %}
                  
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>



    </div>
    {% include "base/footer.html" %}
  </main>


  <!-- category add modal  -->
  <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="categoryadd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-dark p-3">
      <div class="modal-header" style="border-bottom: 2px solid yellow;">
        <h5 class="modal-title text-white" id="exampleModalLabel">Category Add</h5>
        <button type="button" class="close" style="color: yellow;" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="." method="POST" >
          {% csrf_token %}
        {{category_form|crispy}}
       
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-warning">Add category</button>
      </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>


  
<!-- this is the script for categoy management.py -->
  {% block scripts %}
  <!-- this is for the automatic slug creations -->
  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script>
     $('.product_details').on('click',function(e){
      e.preventDefault();
      var self = $(this)
      console.log(self.data('title'))
      console.log(self.attr('href'))
      Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.isConfirmed) {
    Swal.fire(
      'Deleted!',
      'Your file has been deleted.',
      'success'
    )
    location.href = self.attr('href')
  }
}) //
    });
    $('#id_category_name').keypress(function() {
    var dInput = this.value;
    dInput = dInput.replace(/\s+/g, '')
    $('#id_category_slug').val(dInput)
    });

    $('#id_category_slug').keypress(function() {
    var dInput = this.value;
    dInput = dInput.replace(/\s+/g, '')
    $('#id_category_slug').val(dInput)
    });
     // this is for the cofirmation on the delete button
  
    

  </script>
  <!-- this is for the confirmation of delete button using the sweet alert -->

  <script>
   
  </script>


  {% endblock scripts %}




  {% endblock adminbase %}

adminpanel/templates/order_edit_form.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %}
<style>
*{
margin: 0;
} 
input[type='file'] {
  color: rgba(0, 0, 0, 0);

}
input[type=file]::file-selector-button {
  border: 2px solid #e7e55c;
  padding: .2em .4em;
  border-radius: .2em;
  background-color: rgb(209,161,14);
  transition: 1s;
}
.hide{
  display: none;
}
  .product_name{
    color: black;
    font-weight: bolder;
    font-size: 15px;
    position: absolute;
 
  }
  .asteriskField {
    display: none;
}
label{
    color: white;
}
</style>
  
{% endblock css %}
{% block adminbase %}
  
{% include "base/sidebar.html" %}

<main class="main-content position-relative   border-radius-lg " style="height: 50%;">
    {% include "base/nav.html" %}
    {% block pagename %}
    <b>ORDER EDIT</b> 
  {% endblock pagename %}
        <div class="row justify-content-center">
            <div class="col-md-5   m-5 bg-dark p-5" style="border-radius:15px;">
                <form method="POST" action=".">
                          {% csrf_token %}
                          {{forms|crispy}} 
                            <div class="row justify-content-center mt-2">
                                <button type="submit" class="w-50 btn btn-warning p-2 text-center" >UPDATE</button>
                            </div>
                </form>
            </div>
        </div>
    {% include "base/footer.html" %}
  </main>
  
<!-- this is the script for user management -->
  {% block scripts %}
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>

  <script>



// automatic creating slug fields
$('#id_category_name').keyup(function() {
    var dInput = this.value;
    $('#id_category_slug').val(dInput)
});
  </script>
  
  {% endblock scripts %}




  {% endblock adminbase %}