adminpanel/urls.py
from unicodedata import name
from django.urls import  path
from adminpanel import views



urlpatterns = [

    path('',views.adminHome, name='adminhome'),
    path('adminLogin/',views.adminLogin,name='adminLogin'),
    path('adminregister/',views.admin_register,name='adminregister'),
    path('adminLogout/',views.admin_logout,name='adminLogout'),

    # user management
    path('usermanagement/active_inactive/',views.active_inactive_user,name='active_inactive'),
    path('usermanagement/',views.user_management,name='usermanagement'),

    # product management
    path('product_view/',views.product_view,name='product_view'),
    path('product_view/testing', views.single_product, name='single_product'),
    path('product_add/',views.product_add,name='product_add'),
    path('product_update/<int:id>/',views.product_update,name='product_update'),
    path('product_delete/<int:id>/',views.product_delete,name='product_delete'),

    # category management
    path('category_view/', views.category_view, name='category_view'),
    path('category_delete/<int:id>/', views.category_delete, name='category_delete'),
    path('category_edit/<int:id>/', views.category_edit, name='category_edit'),

    # order management
    path('order_view',views.order_management_view,name='order_view'),
    path('order_cancel_admin/<str:order_id>/',views.order_cancel_view,name='order_cancel_admin'),
    path('order_products/',views.order_product_table,name='order_products'),
    path('order_edit/<str:order_id>/',views.order_edit_view,name='order_edit'),

    # coupon_management_view
    path('coupon_management',views.coupon_management_view,name='coupon_management'),
    path('delete_coupon/<str:coupon_id>/',views.delete_coupon_view,name='delete_coupon'),
    path('update_coupon/<str:coupon_id>/',views.update_coupon_view,name='update_coupon'),
    path('active_coupon/<str:coupon_id>/',views.active_coupon_view,name='active_coupon'),
    path('coupon_add/',views.coupon_add_view,name='coupon_add'),

    # product_offer 
    path('product_offer_management/',views.product_offer_mangement_view,name='product_offer_management'),
    path('delete_product_offer/<str:id>/',views.delete_product_offer_view,name='delete_product_offer'),
    path('update_product_offer/<str:id>/',views.edit_product_offer_view,name='update_product_offer'),
    path('active_deactive_product_offer/<str:id>/',views.active_deactive_product_offer_view,name='active_deactive_product_offer'),

    # category offer urls 
    path('category_offer/',views.category_offer_view,name='category_offer'),
    path('delete_category_offer/<str:id>/',views.delete_category_offer_view,name='delete_category_offer'),
    path('update_category_offer/<str:id>/',views.edit_category_offer_view,name='update_category_offer'),
    path('active_deactive_category_offer/<str:id>/',views.active_deactive_category_offer_view,name='active_deactive_category_offer'),

    # admin report urls
    path('admin_report/',views.admin_report_view,name='admin_report'),
 
    
    
    


    

    
]

carts/urls.py
from unicodedata import name
from django.urls import path
from carts import views


urlpatterns = [
    # cart
    path('',views.cart,name='cart'),
    path('add-to-cart/<int:product_id>/',views.add_to_cart,name='add-to-cart'),
    path('delete_cart/<int:cart_id>/',views.delete_cart,name='delete_cart'),
    # checkout
    path('check_out/',views.check_out_view,name='check_out'),
    # buy_now
    
    path('buy_now/<int:product_id>/',views.buy_now_view,name='buy_now'),

    # ajax calls
    path('increment/<int:cart_id>/',views.cart_increment,name='increment'),
    path('decrement/<int:cart_id>/',views.cart_decrement,name='decrement'),
    # user addresee for profile
    path('user_address/',views.User_profile_address,name='user_address'),
    path('coupon_apply',views.coupon_apply_view,name='coupon_apply'),
    path('cancel_coupon',views.cancel_coupon_view,name='cancel_coupon'),
    
]

digtech/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # howe
    path('',views.home,name='home'),
    # admin
    path('amn/',include('adminpanel.urls')),
    # store
    path('store/',include('store.urls')),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('carts.urls')),
    # orders
    path('orders/',include('orders.urls')),
    # this is the paypal urls
     path('paypal/', include('paypal.standard.ipn.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models #start 
from accounts.models import Account
from store.models import Product
from django.core.validators import RegexValidator
from carts.models import Coupon
from django.core.validators import MinValueValidator,MaxValueValidator


# Create your models here.

class Payment(models.Model):
    STATUS = (
        ('PENDING', 'PENDING'),
        ('COMPLETED', 'COMPLETED'),
        ('CANCELLED', 'CANCELLED'),
    )

    
    user = models.ForeignKey(Account,on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)
    status = models.CharField(max_length=10, choices=STATUS, default='PENDING')
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.payment_id



class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
        ('Returned', 'Returned'),
        )
    PAYMENT_MODE = (
        ('COD','COD'),
        ('PAYPAL','PAYPAL'),
        ('RAZOR_PAY','RAZORPAY')
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20,blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, validators=[RegexValidator(r'^\d{1,15}$')])
    email = models.EmailField(max_length=50)
    address_line_1 = models.TextField(max_length=300)
    address_line_2 = models.TextField(max_length=300, blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # for checking the coupons 

    coupon  = models.ForeignKey(Coupon,related_name='orders',on_delete=models.CASCADE,null=True,blank=True)
    discount = models.IntegerField(default=0,validators=[MinValueValidator(0),MaxValueValidator(50)])

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name
    class Meta:
        ordering = ['-created_at','-updated_at']
    




class OrderProduct(models.Model):


    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name
    class Meta:
        ordering= ('-created_at','-updated_at')


class RazorPay(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    razor_pay = models.CharField(max_length=200)
    
    def __str__(self):
        return self.razor_pay

adminpanel/forms.py
from cProfile import label
from django import forms #this is the first line
from django.contrib.auth.models import User
from django.forms import ModelForm
from adminpanel.models import Admin,CategoryOffer,ProductOffer
from carts.models import Coupon
from store.models import Product
from category.models import Category
from orders.models import Order,OrderProduct,Payment

from PIL import Image
from django.core.files import File
import django_filters



class AdminForm(ModelForm):

    password = forms.CharField(widget=forms.PasswordInput(attrs={ 'class': 'form-control'}))
    admin_name = forms.CharField(widget=forms.TextInput(attrs={ 'class' : 'form-control'}))

    class Meta:
        model = Admin
        fields = ['admin_name','password']

class ProductForm(ModelForm):
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))

    # image 1 croping axis
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    # image 3 cropping axis
    """ i am skipping the second image , its already croped from the models plese look there"""
    x_3 = forms.FloatField(widget=forms.HiddenInput())
    y_3 = forms.FloatField(widget=forms.HiddenInput())
    width_3 = forms.FloatField(widget=forms.HiddenInput())
    height_3 = forms.FloatField(widget=forms.HiddenInput())

    # image 4 cropping axis
    x_4 = forms.FloatField(widget=forms.HiddenInput())
    y_4 = forms.FloatField(widget=forms.HiddenInput())
    width_4 = forms.FloatField(widget=forms.HiddenInput())
    height_4 = forms.FloatField(widget=forms.HiddenInput())


    class Meta:
        model = Product
        fields = '__all__'

    def save(self):

        photo = super(ProductForm, self).save()
        photo_3 = super(ProductForm, self).save()
        photo_4  = super(ProductForm,self).save()
        self.is_available= True

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.image_1)
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.image_1.path)

        # image_3 this is for the image 3 axis
        x3 = self.cleaned_data.get('x_3')
        y3 = self.cleaned_data.get('y_3')
        w3 = self.cleaned_data.get('width_3')
        h3 = self.cleaned_data.get('height_3')

        

        image3 = Image.open(photo_3.image_3)
        cropped_image3 = image3.crop((x3, y3, w3+x3, h3+y3))
        resized_image3 = cropped_image3.resize((200, 200), Image.ANTIALIAS)
        resized_image3.save(photo.image_3.path)

        # image_4 this is for the image 4 axis
        x4 = self.cleaned_data.get('x_4')
        y4 = self.cleaned_data.get('y_4')
        w4 = self.cleaned_data.get('width_4')
        h4 = self.cleaned_data.get('height_4')

        

        image4 = Image.open(photo_4.image_4)
        cropped_image4 = image4.crop((x4, y4, w4+x4, h4+y4))
        resized_image4 = cropped_image4.resize((200, 200), Image.ANTIALIAS)
        resized_image4.save(photo.image_4.path)


        return photo,photo_3,photo_4

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class DateInput(forms.DateInput):
    input_type = 'date'

class CouponForm(ModelForm):
    class Meta:
        model = Coupon
        fields = ['coupon_code','valid_from','valid_to','discount','active']
        widgets = {
            'valid_from': DateInput(),
            'valid_to': DateInput(),
        }

# this is for the type setting to date in forms
class DateOnlyInput(forms.DateInput):
    input_type = 'date'


# this is for the ProductOfferForm
class ProductOfferForm(ModelForm):
    class Meta:
        model = ProductOffer
        fields = '__all__'
        widgets = {
            'valid_from': DateOnlyInput(),
            'valid_to': DateOnlyInput(),
        }

# this is for the categoryOfferForm
class CategoryOfferForm(ModelForm):
    class Meta:
        model = CategoryOffer
        fields = '__all__'
        widgets = {
            'valid_from': DateOnlyInput(),
            'valid_to': DateOnlyInput(),
        }
    
# this is for the django filtering for admin report


class OrderFilter(django_filters.FilterSet):
    
    # status = django_filters.CharFilter(field_name='payment__status',lookup_expr='iexact',label='Whatever you want')
    methods = django_filters.CharFilter(field_name='payment__payment_method',lookup_expr='icontains',label='Payment Methods')
    product__product_name = django_filters.CharFilter(field_name='product__product_name',lookup_expr='icontains',label='Product Name')
    product__category__category_name = django_filters.CharFilter(field_name='product__category__category_name',lookup_expr='icontains',label='Category Name')
  
    product_price__lt = django_filters.NumberFilter(field_name='product_price', lookup_expr='lt',label='Price Lessthan')
    product_price__gt = django_filters.NumberFilter(field_name='product_price', lookup_expr='gt',label='Price Greaterthan')

    # created_at__gt = django_filters.NumberFilter(field_name='created_at', lookup_expr='date__gt')
    # created_at__lt = django_filters.NumberFilter(field_name='created_at', lookup_expr='date__lt')

    # created_at = django_filters.NumberFilter(field_name='created_at', lookup_expr='month')


    # this is for the year 
    release_year = django_filters.NumberFilter(field_name='created_at', lookup_expr='year',label='Year')
    release_year__gt = django_filters.NumberFilter(field_name='created_at', lookup_expr='year__gt',label='Greater Than Year')
    release_year__lt = django_filters.NumberFilter(field_name='created_at', lookup_expr='year__lt',label='Less Than Year')

    # this is for the date checking
    created_at = django_filters.DateFilter(
        widget=DateInput(
            attrs={
                'type': 'date',
            }
        ),lookup_expr='date',label='Date Wise'
    )
    created_at__gt = django_filters.DateFilter(field_name='created_at',        
                                                widget=DateInput(attrs={
                                                                        'type': 'date',
                                                                    }),lookup_expr='date__gt',label='Date Greater Than')
    created_at__lt = django_filters.DateFilter(field_name='created_at',widget=DateInput(attrs={
                                                                        'type': 'date',
                                                                    }),lookup_expr='date__lt',label = 'Date Less Than')

    # # crated_month = django_filters.CharFilter(field_name='created_at',widget=DateInput(attrs={
    #                                                                     'type': 'year',
    #                                                                 }),lookup_expr='contains',)



    # created_at__lt= django_filters.DateFromToRangeFilter()

    class Meta:
        model = OrderProduct
        fields = ['payment__status','product__category',]


                

adminpanel/templates/report_admin/admin_report.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block adminbase %}
{% block css %}
<style>

input[type='file'] {
  color: rgba(0, 0, 0, 0);

}
input[type=file]::file-selector-button {
  border: 2px solid #e7e55c;
  padding: .2em .4em;
  border-radius: .2em;
  background-color: rgb(209,161,14);
  transition: 1s;
}
.hide{
  display: none;
}
  .product_name{
    color: black;
    font-weight: bolder;
    font-size: 15px;
    position: absolute;
 
  }
  .asteriskField {
    display: none;
} 
#id_payment__status,#id_methods,#id_product__product_name,#id_product__category,#id_product_price__lt,#id_product_price__gt,#date-time-edit,#id_created_at__gt,#id_release_year{
  background-color:#FFD333;
}
#id_created_at,#id_created_at__lt,#id_release_year__gt,#id_release_year__lt{
  background-color:#FFD333;
}

  .product_name:hover{
    color: rgb(209, 209, 5);
    text-decoration: none;
    font-size: 17px;
    cursor: w-resize;
  }
  label{
    color: white;
  }
  .alert-error{
    background-color: rgba(255, 0, 0, 0.377);
  }
  #coupon:hover{
    color: black;
  }
</style>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
  
<!-- <script src="https://raw.githack.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script> -->

{% endblock css %}
  


<main class="main-content position-relative border-radius-lg " style="height: 100vh;">
    {% include "base/nav.html" %}


    {% block pagename %}
    <b>ADMIN REPORT</b> 
  {% endblock pagename %}

  


    <div class="row justify-content-center mt-5">
              {% if messages %}
                    

              {% for message in messages %}
            
                <div class="alert col-md-4 alert-{{ message.tags }} text-center" role="alert">
                      {{ message }}
                </div>

              {% endfor %}
                  
                    
              {% endif %}
    </div>


<div class="container-fluid "  style="">

 

  
      <div class="row text-center">


         <!-- testing jithin -->

        
            <div class="col-md-3 p-3 bg-dark" style=" border-radius: 15px;">



              <div class="card bg-dark">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                              <div class="bg-gradient-primary shadow-primary border-radius-lg p-4 pb-3" style="display: flex; justify-content:center; ">
                                <h5> CHOOSE YOUR OPTIONS <a href="{% url 'adminhome' %}"><i class="fa-solid fa-house-user"></i></a></h5>

                              </div>
                        </div>
                        <div class="card-body  bg-dark">


                                  <form action="" method="get">
                                    <div class="row">
                                      <div class="col-md-6 ">
                                        {{filter.form.payment__status|as_crispy_field }}
                                        
                                      </div>
                                      <div class="col-md-6 ">
                                        {{filter.form.methods|as_crispy_field }}
                                        
                                      </div>
                                    </div>

                                    <div class="row">
                                      <div class="col-md-6 ">
                                        {{filter.form.product__product_name|as_crispy_field }}
                                        
                                      </div>
                                      <div class="col-md-6">
                                        {{filter.form.product__category|as_crispy_field }}
                                        
                                      </div>
                                    </div>

                                    <div class="row">
                                      <div class="col-md-6 ">
                                        {{filter.form.product_price__lt|as_crispy_field }}
                                        
                                      </div>
                                      <div class="col-md-6 ">
                                        {{filter.form.product_price__gt|as_crispy_field }}
                                        
                                      </div>
                                    </div>

                                    <div class="row">
                                      <div class="col-md-12 ">
                                        {{ filter.form.created_at|as_crispy_field }}
                                      </div>
                      
                                    </div>

                                    
                                    <div class="row">
                                      <div class="col-md-6">
                                        {{filter.form.created_at__gt|as_crispy_field }}
                                        
                                        
                                      </div>
                                      <div class="col-md-6 ">
                                        
                                        {{filter.form.created_at__lt|as_crispy_field }}
                                        
                                      </div>
                                    </div>


                                    <div class="row">
                                      <div class="col-md-12 ">
                                        
                                        {{filter.form.release_year|as_crispy_field }}
                                        
                                      </div>
                                    </div>

                                    <div class="row">
                                      <div class="col-md-6 ">
                                        {{filter.form.release_year__gt|as_crispy_field }}
                                      </div>
                                      <div class="col-md-6 ">
                                        {{filter.form.release_year__lt|as_crispy_field }}
                                      </div>
                                    </div>

                                    

                                    
                                    
                                    


                                  <button class="btn btn-warning"> SEARCH </button>
                                </form>
                    
                        </div>
              </div>
              
            </div>


            <div class="col-md-9">
            <div class="card ">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                              <div class="bg-gradient-primary shadow-primary border-radius-lg p-4 pb-3" style="display: flex; gap: 12px; ">
                                  <div style="">
                                      <a href="?pdf='pdf'" class="btn btn-dark m-0"><b>PDF</b></a>
                                  </div>
                                  <div style="">
                                    <a href="?csv='csv'" id="csv_id" class="btn btn-dark m-0"><b>CSV</b></a>
                                </div>
                              </div>
                        </div>
                        <div class="card-body px-0 pb-2">
                        <div class="table-responsive p-5">
                            <table id="table" class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"><b>ORDER NUMBER </b></th>
                                <th class="text-uppercase  text-center text-secondary text-xxs font-weight-bolder opacity-7"><b>PRODUCT NAME</b></th>
                                <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7"><b>PAYMENT STATUS</b></th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"><b>PAYMENT METHOD</b></th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"><b>CATEGORY </b></th>
                                <th class="text-uppercase text-center text-secondary text-xxs font-weight-bolder opacity-7"><b>ORDER AMOUNT</b></th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"><b>Valid to</b></th>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7"><b>Discount % </b></th>
                                </tr>
                            </thead>
                            <tbody>

                  
                 

                                {% for order in  filter_query_set %}
                                <tr>
                                    <td>
                                    
                                    <p class="text-xs text-center font-weight-bold mb-0">{{ forloop.counter }}</p>
                                    </td>
                                    <td>
                                    <p class="text-xs text-center font-weight-bold mb-0">{{order.product.product_name}}</p>
                                    </td>

                                    <td>
                                    <p class="text-xs text-center font-weight-bold mb-0">{{order.payment.status}}</p>
                                    </td>

                                    <td>
                                    <p class="text-xs text-center font-weight-bold mb-0">{{order.payment.payment_method}}</p>
                                    </td>

                                    <td>
                                    <p class="text-xs text-center font-weight-bold mb-0">{{order.product.category.category_name}}</p>
                                    </td>

                                    <td>
                                      <p class="text-xs text-center font-weight-bold mb-0">{{order.product_price}}</p>
                                    </td>

                                    <td>
                                      <p class="text-xs text-center font-weight-bold mb-0">{{order.created_at|date}}</p>
                                    </td>

                                    
                                    <td>
                                      <p class="text-xs text-center font-weight-bold mb-0">{{order.created_at|date:"M"}}</p>
                                    </td>

                
                                    
                                
 
                                    
                                    
                                    
                                
                                </tr>
                                
                                {% endfor %}
                            
                            </tbody>
                            </table>
                        </div>
                        </div>
            </div>
            </div>
      </div>

        
</div>

  </main>


<!-- Modal view and update modaal -->

<!-- this is the script for user management -->
  {% block scripts %}
  

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.css"/>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
  <!-- needed to use moment.js for  date sorting-->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.19/sorting/datetime-moment.js"></script>
  <Script>
  
    $(document).ready( function () {
  
  $.fn.dataTable.moment( 'MMM D, YYYY' );
  $.fn.dataTable.moment( 'D-MMM-YY' );
  $('#table').DataTable({
  
  dom: 'B<"clear">lfrtip',
  buttons: {
      name: 'primary',
      buttons: [ 'copy', 'csv', 'excel', 'pdf' ]
  
      }}
  );
  });

  // testing for the window.location.search
  function csvFunction(){
    const urlcsv = window.location.search
    const urlhref =  document.getElementById('csv_id').href 
    document.getElementById('csv_id').href = urlcsv+urlhref
    
  }
  </Script>
  

  {% endblock scripts %}




  {% endblock adminbase %}